-- RosterLlama PostgreSQL production foundation
CREATE TABLE IF NOT EXISTS organizations(id text PRIMARY KEY,name text NOT NULL,slug text UNIQUE NOT NULL,stripe_account_id text,payments_status text NOT NULL DEFAULT 'not_connected',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS families(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name text,email text NOT NULL,phone text,password_hash text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,email));
CREATE TABLE IF NOT EXISTS participants(id text PRIMARY KEY,family_id text NOT NULL REFERENCES families(id) ON DELETE CASCADE,name text NOT NULL,birth_date date,allergies text,emergency_contact text,authorized_pickups jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS programs(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name text NOT NULL,price integer NOT NULL DEFAULT 0,questions jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(id text PRIMARY KEY,program_id text NOT NULL REFERENCES programs(id) ON DELETE CASCADE,label text NOT NULL,capacity integer NOT NULL CHECK(capacity>=0),status text NOT NULL DEFAULT 'open',starts_at timestamptz,ends_at timestamptz,price integer,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS registrations(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,session_id text NOT NULL REFERENCES sessions(id),participant_id text NOT NULL REFERENCES participants(id),status text NOT NULL,payment_status text NOT NULL DEFAULT 'pending',waitlist_id text,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS one_active_registration ON registrations(session_id,participant_id) WHERE status='enrolled';
CREATE TABLE IF NOT EXISTS waitlist(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,session_id text NOT NULL REFERENCES sessions(id),participant_id text NOT NULL REFERENCES participants(id),status text NOT NULL DEFAULT 'waiting',offer_expires_at timestamptz,accepted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payments(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,registration_id text NOT NULL REFERENCES registrations(id),amount integer NOT NULL CHECK(amount>=0),status text NOT NULL,processor_id text UNIQUE,idempotency_key text UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS refunds(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,registration_id text NOT NULL REFERENCES registrations(id),payment_id text REFERENCES payments(id),amount integer NOT NULL CHECK(amount>0),status text NOT NULL,reason text,note text,processor_id text UNIQUE,idempotency_key text UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_log(id text PRIMARY KEY,organization_id text REFERENCES organizations(id) ON DELETE CASCADE,actor_type text,actor_id text,action text NOT NULL,detail jsonb,created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS data_migrations(id text PRIMARY KEY,completed_at timestamptz NOT NULL DEFAULT now(),detail jsonb);
